### ISSUE TITLE
License Grant: provide dialog to edit "Condition Expression"

### ISSUE THREAD

**Issue by ruspl-afed** [arsysop/passage-loc#22]
The dialog should provide multiline (styled) text and accept values copied from HW Inspector dialog and convert values to model:
- the segment is `name=value with spaces\n`
- silently remove all empty strings
- report (and remove) invalid segments 
- convert `\n` to `;` for valid segments for dialog to model trnalsation
- convert `;` to `\n` for valid segments for model to dialog translation

The model value:
```
baseboard.version=Version 1.0;firmware.manufacturer=A company
```
The dialog value:
```
baseboard.version=Version 1.0
firmware.manufacturer=A company
```

**Comment by serjiokov** [comment]
Service, renderer and dialog implemented
